### ISSUE TITLE
error: `goradf' undefined

### ISSUE THREAD

**Issue by florisvb** [strawlab/MultiCamSelfCal#3]
When running with "Do-Global-Iterations: 1", we get the following error:

error: `goradf' undefined near line 368 column 17
error: called from:
error:   gocal.m at line 368, column 15

This follows a whole bunch of warnings about the path, so I suspect its something simple. Anyhow, this can be obtained with the new test dataset committed in 489ac97df1fd530dd8b0743a735ae8e5e3686e9f . Just run::

  octave gocal.m --config='../strawlab/test-data/DATA20100906_134124'

**Comment by davebenson** [comment]
I don't seem to experience this problem.  Are you actually running gocal.m from within its directory?  I notice that the goradf function is invoked as:
    cd ../CalTechCal
    selfcalib = goradf(config,selfcal.par2estimate,INL_TOL);
    cd ../MultiCamSelfCal
which obviously won't work if you run gocal.m from another directory.  We should probably call add_path() instead of this 'cd' hackery.

**Comment by astraw** [comment]
We're not having this problem. Closing for now. Reopen if it is still an issue.
