### ISSUE TITLE
-ASCII error in Octave 3.2.3

### ISSUE THREAD

**Issue by fieldbio** [strawlab/MultiCamSelfCal#5]
Not sure if this is a problem with the current version of Octave, but with 3.2.2 gocal doesn't run because the Octave save function uses the parameter '-ascii' instead of '-ASCII'. This is remedied by changing the uppercase to lowercase option in:

gocal.m
im2imstat.m
im2points.m
joinoscars.m
savecalpar.m

**Comment by astraw** [comment]
Hmm, things are working as they are for us. So I'm closing this now, but please reopen it if it hits you again.
