### ISSUE TITLE
Octave warns about Matlab-style short-circuit operation

### ISSUE THREAD

**Issue by FlorianFranzen** [strawlab/MultiCamSelfCal#7]
When I run ```gocal.m``` in octave 4.0.0 I get a lot of warnings:
```
warning: Matlab-style short-circuit operation performed for operator |
warning: Matlab-style short-circuit operation performed for operator &
```

For me the simplest fix was to disable warnings of this kind:
```
warning('off', 'Octave:possible-matlab-short-circuit-operator');
```

That is of course not an optimal solution, so maybe there is a proper fix, e.g. by using short-circuit free operations.

**Comment by astraw** [comment]
Thanks for the report and sorry about the long delay.
